#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#index:
#    path: /
#    controller: App\Controller\MainController::index

# marmiton:
#    path: /
#    controller: App\Controller\HelloController::world
